import pc from 'picocolors';

const API_BASE = process.env.API_BASE || 'http://localhost:3001/api';

const COUNTS = {
  tags: Number(process.env.SEED_TAGS || 16),
  characters: Number(process.env.SEED_CHARACTERS || 80),
  notes: Number(process.env.SEED_NOTES || 260),
  timeline: Number(process.env.SEED_TIMELINE || 120),
  factions: Number(process.env.SEED_FACTIONS || 18),
  dynasties: Number(process.env.SEED_DYNASTIES || 8),
  markers: Number(process.env.SEED_MARKERS || 180),
  territories: Number(process.env.SEED_TERRITORIES || 28),
};

function randomColor() {
  return `#${Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, '0')}`;
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

async function api(path, options = {}) {
  const res = await fetch(`${API_BASE}${path}`, {
    headers: {
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
    ...options,
  });
  const text = await res.text();
  const data = text ? JSON.parse(text) : null;
  return { ok: res.ok, status: res.status, data };
}

function mustOk(result, context) {
  if (!result.ok) {
    throw new Error(`${context}: status=${result.status} payload=${JSON.stringify(result.data, null, 2)}`);
  }
}

async function main() {
  console.log(pc.bold(pc.magenta('\nCampaigner demo seed')));
  console.log(pc.dim(`API: ${API_BASE}`));
  console.log(pc.dim(`Counts: ${JSON.stringify(COUNTS)}\n`));

  const projectRes = await api('/projects', {
    method: 'POST',
    body: JSON.stringify({
      name: `Demo Seed ${Date.now()}`,
      description: 'Auto-generated dataset for performance and QA',
    }),
  });
  mustOk(projectRes, 'create project');
  const projectId = projectRes.data?.data?.id;
  if (!projectId) throw new Error('create project: missing project id');
  console.log(pc.green(`✔ Project created: #${projectId}`));

  const rootMapRes = await api(`/projects/${projectId}/maps/root`);
  mustOk(rootMapRes, 'get root map');
  const rootMapId = rootMapRes.data?.data?.id;
  if (!rootMapId) throw new Error('root map id is missing');
  console.log(pc.green(`✔ Root map: #${rootMapId}`));

  const tagIds = [];
  for (let i = 0; i < COUNTS.tags; i += 1) {
    const res = await api('/tags', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        name: `seed-tag-${i + 1}`,
        color: randomColor(),
      }),
    });
    mustOk(res, `create tag ${i + 1}`);
    tagIds.push(res.data?.data?.id);
  }
  console.log(pc.green(`✔ Tags seeded: ${tagIds.length}`));

  const characterIds = [];
  for (let i = 0; i < COUNTS.characters; i += 1) {
    const res = await api('/characters', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        name: `Seed Character ${i + 1}`,
        title: `Role ${i % 7}`,
        race: ['Human', 'Elf', 'Dwarf', 'Orc'][i % 4],
        characterClass: ['Warrior', 'Mage', 'Rogue', 'Cleric'][i % 4],
        level: randomInt(1, 20),
        status: ['alive', 'unknown', 'missing'][i % 3],
        bio: 'Generated by seed-demo script.',
      }),
    });
    mustOk(res, `create character ${i + 1}`);
    characterIds.push(res.data?.data?.id);
  }
  console.log(pc.green(`✔ Characters seeded: ${characterIds.length}`));

  const noteIds = [];
  for (let i = 0; i < COUNTS.notes; i += 1) {
    const noteType = i % 7 === 0 ? 'wiki' : 'note';
    const res = await api('/notes', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        title: `Seed Note ${i + 1}`,
        content: `# Seed note ${i + 1}\n\nThis is generated content block ${i + 1}.`,
        format: 'md',
        noteType,
        isPinned: i % 15 === 0,
      }),
    });
    mustOk(res, `create note ${i + 1}`);
    noteIds.push(res.data?.data?.id);
  }
  console.log(pc.green(`✔ Notes seeded: ${noteIds.length}`));

  for (let i = 0; i < COUNTS.timeline; i += 1) {
    const res = await api('/timeline', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        title: `Seed Event ${i + 1}`,
        description: 'Generated timeline event',
        eventDate: `Year ${100 + i}`,
        sortOrder: i,
        era: i < 40 ? 'Ancient' : i < 80 ? 'Middle' : 'Modern',
        linkedNoteId: noteIds[i % noteIds.length] ?? null,
      }),
    });
    mustOk(res, `create timeline event ${i + 1}`);
  }
  console.log(pc.green(`✔ Timeline events seeded: ${COUNTS.timeline}`));

  const factionIds = [];
  for (let i = 0; i < COUNTS.factions; i += 1) {
    const res = await api('/factions', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        name: `Seed Faction ${i + 1}`,
        type: 'guild',
        motto: 'Generated order',
        description: 'Generated faction',
        status: 'active',
        parentFactionId: null,
      }),
    });
    mustOk(res, `create faction ${i + 1}`);
    factionIds.push(res.data?.data?.id);
  }
  console.log(pc.green(`✔ Factions seeded: ${factionIds.length}`));

  for (let i = 0; i < COUNTS.dynasties; i += 1) {
    const res = await api('/dynasties', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        name: `Seed Dynasty ${i + 1}`,
        motto: 'Generated bloodline',
        description: 'Generated dynasty',
        history: 'Created by seed-demo',
        status: 'active',
        color: '#c9a959',
        secondaryColor: '#2a2a4a',
        foundedDate: `Year ${i + 1}`,
        extinctDate: '',
        linkedFactionId: factionIds[i % factionIds.length] ?? null,
      }),
    });
    mustOk(res, `create dynasty ${i + 1}`);
  }
  console.log(pc.green(`✔ Dynasties seeded: ${COUNTS.dynasties}`));

  for (let i = 0; i < COUNTS.markers; i += 1) {
    const res = await api(`/maps/${rootMapId}/markers`, {
      method: 'POST',
      body: JSON.stringify({
        title: `Seed Marker ${i + 1}`,
        description: 'Generated marker',
        positionX: Math.random(),
        positionY: Math.random(),
        color: randomColor(),
        icon: 'custom',
        linkedNoteId: noteIds[i % noteIds.length] ?? null,
        childMapId: null,
      }),
    });
    mustOk(res, `create marker ${i + 1}`);
  }
  console.log(pc.green(`✔ Markers seeded: ${COUNTS.markers}`));

  for (let i = 0; i < COUNTS.territories; i += 1) {
    const baseX = Math.random() * 0.7;
    const baseY = Math.random() * 0.7;
    const points = [
      { x: baseX, y: baseY },
      { x: Math.min(0.98, baseX + 0.08 + Math.random() * 0.1), y: baseY + 0.01 },
      { x: Math.min(0.98, baseX + 0.05 + Math.random() * 0.08), y: Math.min(0.98, baseY + 0.09 + Math.random() * 0.08) },
      { x: baseX + 0.01, y: Math.min(0.98, baseY + 0.07 + Math.random() * 0.08) },
    ];

    const res = await api(`/maps/${rootMapId}/territories`, {
      method: 'POST',
      body: JSON.stringify({
        name: `Seed Territory ${i + 1}`,
        description: 'Generated territory',
        color: randomColor(),
        opacity: 0.22 + Math.random() * 0.2,
        borderColor: randomColor(),
        borderWidth: 1.2 + Math.random() * 1.5,
        smoothing: Math.random() * 0.35,
        factionId: factionIds[i % factionIds.length] ?? null,
        sortOrder: i,
        points,
      }),
    });
    mustOk(res, `create territory ${i + 1}`);
  }
  console.log(pc.green(`✔ Territories seeded: ${COUNTS.territories}`));

  console.log(pc.bold(pc.green(`\nDone. Seed project id: ${projectId}\n`)));
}

main().catch((error) => {
  console.error(pc.red(error.stack || error.message));
  process.exitCode = 1;
});
