export function createSmokeContext() {
  return {
    projectId: null,
    tagId: null,
    characterId: null,
    secondaryCharacterId: null,
    relationshipId: null,
    rootMapId: null,
    markerId: null,
    territoryId: null,
    noteId: null,
    secondaryWikiNoteId: null,
    wikiLinkId: null,
    timelineEventId: null,
    secondaryTimelineEventId: null,
    factionId: null,
    secondaryFactionId: null,
    factionRankId: null,
    factionMemberId: null,
    factionRelationId: null,
    dynastyId: null,
    dogmaId: null,
    secondaryDogmaId: null,
    importedProjectId: null,
    overlayBranchId: null,
    uniqueCharacterName: null,
    uniqueSecondaryCharacterName: null,
    uniqueNoteTitle: null,
    uniqueTimelineTitle: null,
    uniqueDogmaTitle: null,
  };
}