const { chromium } = require('playwright')

;(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--enable-webgl'] })
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })

  await page.goto('http://localhost:5173/?mode=curve', { waitUntil: 'networkidle' })
  await page.waitForTimeout(1500)
  const curveCanvas = page.locator('.canvas-host canvas')
  const cb = await curveCanvas.boundingBox()
  if (!cb) throw new Error('curve canvas missing')
  await page.mouse.move(cb.x + cb.width * 0.5, cb.y + cb.height * 0.45)
  await page.mouse.down()
  await page.mouse.move(cb.x + cb.width * 0.5 + 40, cb.y + cb.height * 0.45, { steps: 5 })
  await page.mouse.up()
  await page.waitForTimeout(300)

  await page.goto('http://localhost:5173/?mode=large', { waitUntil: 'networkidle' })
  await page.waitForFunction(() => window.__proto001LargeReady === true, { timeout: 60_000 })
  const largeCanvas = page.locator('.canvas-host canvas')
  const lb = await largeCanvas.boundingBox()
  if (!lb) throw new Error('large canvas missing')
  await page.mouse.move(lb.x + lb.width / 2, lb.y + lb.height / 2)
  await page.mouse.down()
  await page.mouse.move(lb.x + lb.width / 2 + 80, lb.y + lb.height / 2 + 60, { steps: 8 })
  await page.mouse.up()

  await browser.close()
  console.log('smoke ok')
})()
