/**
 * Системные политические шкалы (сид). Коды глобально уникальны.
 */
export type SeedPoliticalScale = {
  code: string;
  entityType: 'state' | 'faction';
  category: string;
  name: string;
  leftPoleLabel: string;
  rightPoleLabel: string;
  leftPoleDescription: string;
  rightPoleDescription: string;
  zonesJson: string | null;
  sortOrder: number;
};

export const SYSTEM_POLITICAL_SCALES_SEED: SeedPoliticalScale[] = [
  // --- state / power ---
  {
    code: 'authoritarianism_democracy',
    entityType: 'state',
    category: 'power',
    name: 'Авторитаризм ↔ Демократия',
    leftPoleLabel: 'Авторитаризм',
    rightPoleLabel: 'Демократия',
    leftPoleDescription: 'Сильная концентрация власти, ограниченные институты участия.',
    rightPoleDescription: 'Широкое политическое участие и конкурентные выборы.',
    zonesJson: JSON.stringify([
      { from: -100, to: -66, label: 'Тирания / диктатура', description: 'Правление одного центра без эффективных ограничений.' },
      { from: -65, to: -20, label: 'Авторитарный режим', description: 'Формальные институты есть, но оппозиция слаба.' },
      { from: -19, to: 19, label: 'Гибридный режим', description: 'Смесь демократических и авторитарных практик.' },
      { from: 20, to: 65, label: 'Представительная демократия', description: 'Выборы и парламент как основа легитимности.' },
      { from: 66, to: 100, label: 'Прямая демократия', description: 'Максимум прямого участия граждан в решениях.' },
    ]),
    sortOrder: 1,
  },
  {
    code: 'centralization_federalization',
    entityType: 'state',
    category: 'power',
    name: 'Централизация ↔ Федерализация',
    leftPoleLabel: 'Централизация',
    rightPoleLabel: 'Федерализация',
    leftPoleDescription: 'Решения и ресурсы сосредоточены в столице.',
    rightPoleDescription: 'Регионы и субъекты обладают существенной автономией.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Унитарное государство', description: 'Единая административная вертикаль.' },
      { from: -49, to: 20, label: 'Деволюция', description: 'Постепенная передача полномочий вниз.' },
      { from: 21, to: 65, label: 'Федерация', description: 'Чёткое разделение уровней власти.' },
      { from: 66, to: 100, label: 'Конфедерация', description: 'Союз с высокой независимостью членов.' },
    ]),
    sortOrder: 2,
  },
  {
    code: 'monarchy_republic',
    entityType: 'state',
    category: 'power',
    name: 'Монархия ↔ Республика',
    leftPoleLabel: 'Монархия',
    rightPoleLabel: 'Республика',
    leftPoleDescription: 'Наследуемая верховная власть и символика престола.',
    rightPoleDescription: 'Выборные органы и отсутствие наследственной власти.',
    zonesJson: JSON.stringify([
      { from: -100, to: -66, label: 'Абсолютная монархия', description: 'Монарх — главный источник законов.' },
      { from: -65, to: -20, label: 'Конституционная монархия', description: 'Парламент и закон ограничивают монарха.' },
      { from: -19, to: 19, label: 'Смешанная форма', description: 'Черты монархии и республики в равновесии.' },
      { from: 20, to: 65, label: 'Парламентская республика', description: 'Правительство отвечает перед парламентом.' },
      { from: 66, to: 100, label: 'Президентская республика', description: 'Сильная исполнительная власть президента.' },
    ]),
    sortOrder: 3,
  },
  {
    code: 'theocracy_secularism',
    entityType: 'state',
    category: 'power',
    name: 'Теократия ↔ Секуляризм',
    leftPoleLabel: 'Теократия',
    rightPoleLabel: 'Секуляризм',
    leftPoleDescription: 'Религиозное право и духовенство в основе государства.',
    rightPoleDescription: 'Нейтральность государства в религиозных вопросах.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Теократия', description: 'Богословские нормы определяют закон.' },
      { from: -49, to: -10, label: 'Государственная религия', description: 'Официальный культ и привилегии церкви.' },
      { from: -9, to: 30, label: 'Религия в публичной жизни', description: 'Заметное присутствие религии в символике и нормах.' },
      { from: 31, to: 100, label: 'Светское государство', description: 'Разделение сфер и равенство конфессий.' },
    ]),
    sortOrder: 4,
  },
  // --- state / society ---
  {
    code: 'police_state_civil_liberties',
    entityType: 'state',
    category: 'society',
    name: 'Полицейское государство ↔ Гражданские свободы',
    leftPoleLabel: 'Полицейское государство',
    rightPoleLabel: 'Гражданские свободы',
    leftPoleDescription: 'Сильный контроль, ограничения приватности и собраний.',
    rightPoleDescription: 'Широкие права на слово, ассоциации и судебную защиту.',
    zonesJson: null,
    sortOrder: 5,
  },
  {
    code: 'traditionalism_progressivism',
    entityType: 'state',
    category: 'society',
    name: 'Традиционализм ↔ Прогрессивизм',
    leftPoleLabel: 'Традиционализм',
    rightPoleLabel: 'Прогрессивизм',
    leftPoleDescription: 'Опора на устойчивые нормы, роль общины и религии.',
    rightPoleDescription: 'Ориентация на реформы, права меньшинств и новые нормы.',
    zonesJson: null,
    sortOrder: 6,
  },
  {
    code: 'estate_meritocracy',
    entityType: 'state',
    category: 'society',
    name: 'Сословность ↔ Меритократия',
    leftPoleLabel: 'Сословность',
    rightPoleLabel: 'Меритократия',
    leftPoleDescription: 'Статус и доступ к власти зависят от происхождения.',
    rightPoleDescription: 'Карьера и роли по компетенции и заслугам.',
    zonesJson: null,
    sortOrder: 7,
  },
  {
    code: 'monoethnic_multicultural',
    entityType: 'state',
    category: 'society',
    name: 'Моноэтничность ↔ Мультикультурализм',
    leftPoleLabel: 'Моноэтничность',
    rightPoleLabel: 'Мультикультурализм',
    leftPoleDescription: 'Один культурный образ государства и ассимиляционные ожидания.',
    rightPoleDescription: 'Поддержка культурного разнообразия и интеграции.',
    zonesJson: null,
    sortOrder: 8,
  },
  // --- state / economy ---
  {
    code: 'planned_market',
    entityType: 'state',
    category: 'economy',
    name: 'Плановая ↔ Рыночная экономика',
    leftPoleLabel: 'Плановая',
    rightPoleLabel: 'Рыночная',
    leftPoleDescription: 'Централизованное планирование и квоты.',
    rightPoleDescription: 'Цены и конкуренция как основной регулятор.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Командно-административная', description: 'Планы и распределение сверху.' },
      { from: -49, to: -10, label: 'Регулируемая плановая', description: 'План с местом для рыночных элементов.' },
      { from: -9, to: 30, label: 'Смешанная экономика', description: 'Государство и рынок делят ключевые рычаги.' },
      { from: 31, to: 70, label: 'Рыночная с регулированием', description: 'Рынок доминирует, регулирование точечное.' },
      { from: 71, to: 100, label: 'Свободный рынок', description: 'Минимум барьеров и вмешательств.' },
    ]),
    sortOrder: 9,
  },
  {
    code: 'protectionism_free_trade',
    entityType: 'state',
    category: 'economy',
    name: 'Протекционизм ↔ Свободная торговля',
    leftPoleLabel: 'Протекционизм',
    rightPoleLabel: 'Свободная торговля',
    leftPoleDescription: 'Тарифы и квоты для защиты отечественных отраслей.',
    rightPoleDescription: 'Минимальные барьеры для импорта и экспорта.',
    zonesJson: null,
    sortOrder: 10,
  },
  {
    code: 'agrarian_industrial',
    entityType: 'state',
    category: 'economy',
    name: 'Аграрность ↔ Индустриализация',
    leftPoleLabel: 'Аграрность',
    rightPoleLabel: 'Индустриализация',
    leftPoleDescription: 'Сельское хозяйство и земля как основа экономики.',
    rightPoleDescription: 'Промышленность, сервисы и инновации доминируют.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Аграрное общество', description: 'Большинство занято землёй и природными циклами.' },
      { from: -49, to: 0, label: 'Аграрно-промышленное', description: 'Переходные отрасли и урбанизация.' },
      { from: 1, to: 50, label: 'Индустриальное', description: 'Заводы, инфраструктура, массовое производство.' },
      { from: 51, to: 100, label: 'Постиндустриальное', description: 'Услуги, ИТ, наука и глобальные цепочки.' },
    ]),
    sortOrder: 11,
  },
  {
    code: 'state_private_property',
    entityType: 'state',
    category: 'economy',
    name: 'Казённая собственность ↔ Частная собственность',
    leftPoleLabel: 'Казённая собственность',
    rightPoleLabel: 'Частная собственность',
    leftPoleDescription: 'Государственные и общинные активы в центре модели.',
    rightPoleDescription: 'Частные права и рынок активов как норма.',
    zonesJson: null,
    sortOrder: 12,
  },
  // --- state / foreign ---
  {
    code: 'isolationism_expansionism',
    entityType: 'state',
    category: 'foreign',
    name: 'Изоляционизм ↔ Экспансионизм',
    leftPoleLabel: 'Изоляционизм',
    rightPoleLabel: 'Экспансионизм',
    leftPoleDescription: 'Минимальное внешнее вмешательство и автономия.',
    rightPoleDescription: 'Активное расширение влияния и интересов за рубежом.',
    zonesJson: null,
    sortOrder: 13,
  },
  {
    code: 'militarism_pacifism',
    entityType: 'state',
    category: 'foreign',
    name: 'Милитаризм ↔ Пацифизм',
    leftPoleLabel: 'Милитаризм',
    rightPoleLabel: 'Пацифизм',
    leftPoleDescription: 'Высокая роль армии и силовых структур в политике.',
    rightPoleDescription: 'Приоритет дипломатии и отказ от силовых решений.',
    zonesJson: null,
    sortOrder: 14,
  },
  {
    code: 'sovereignty_integration',
    entityType: 'state',
    category: 'foreign',
    name: 'Суверенитет ↔ Интеграция',
    leftPoleLabel: 'Суверенитет',
    rightPoleLabel: 'Интеграция',
    leftPoleDescription: 'Полный контроль над законами и границами.',
    rightPoleDescription: 'Уступка полномочий союзам и наднациональным органам.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Полная независимость', description: 'Нет обязательств, выше национальный суверенитет.' },
      { from: -49, to: 0, label: 'Союзнические отношения', description: 'Договоры и координация без уступки суверенитета.' },
      { from: 1, to: 50, label: 'Конфедеративные структуры', description: 'Совместные институты с разделением компетенций.' },
      { from: 51, to: 100, label: 'Наднациональный союз', description: 'Глубокая интеграция законов и политик.' },
    ]),
    sortOrder: 15,
  },
  {
    code: 'xenophobia_openness',
    entityType: 'state',
    category: 'foreign',
    name: 'Ксенофобия ↔ Открытость',
    leftPoleLabel: 'Ксенофобия',
    rightPoleLabel: 'Открытость',
    leftPoleDescription: 'Опасение чужого, жёсткие барьеры для приезжих.',
    rightPoleDescription: 'Миграция и обмен как норма и ресурс.',
    zonesJson: null,
    sortOrder: 16,
  },

  // --- faction / authority ---
  {
    code: 'loyalism_opposition',
    entityType: 'faction',
    category: 'authority',
    name: 'Лоялизм ↔ Оппозиция',
    leftPoleLabel: 'Лоялизм',
    rightPoleLabel: 'Оппозиция',
    leftPoleDescription: 'Поддержка текущей власти и легитимных институтов.',
    rightPoleDescription: 'Критика режима и стремление к смене курса.',
    zonesJson: null,
    sortOrder: 1,
  },
  {
    code: 'reformism_revolution',
    entityType: 'faction',
    category: 'authority',
    name: 'Реформизм ↔ Революционность',
    leftPoleLabel: 'Реформизм',
    rightPoleLabel: 'Революционность',
    leftPoleDescription: 'Постепенные изменения в рамках системы.',
    rightPoleDescription: 'Резкий разрыв с прежним порядком.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Консерваторы', description: 'Сопротивление переменам, сохранение статус-кво.' },
      { from: -49, to: 0, label: 'Реформисты', description: 'Эволюция правил и институтов.' },
      { from: 1, to: 50, label: 'Радикальные реформисты', description: 'Быстрые преобразования без насильственного переворота.' },
      { from: 51, to: 100, label: 'Революционеры', description: 'Насильственная смена системы как допустимая цель.' },
    ]),
    sortOrder: 2,
  },
  {
    code: 'legalism_underground',
    entityType: 'faction',
    category: 'authority',
    name: 'Легализм ↔ Подпольность',
    leftPoleLabel: 'Легализм',
    rightPoleLabel: 'Подпольность',
    leftPoleDescription: 'Публичная регистрация и работа в правовом поле.',
    rightPoleDescription: 'Тайные структуры и обход официальных запретов.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Официальная партия', description: 'Полностью легальный статус и доступ к институтам.' },
      { from: -49, to: 0, label: 'Полулегальное движение', description: 'Частичная легальность, зона серых схем.' },
      { from: 1, to: 50, label: 'Нелегальное движение', description: 'Запрещённая деятельность без глубокой конспирации.' },
      { from: 51, to: 100, label: 'Подпольная организация', description: 'Строгая конспирация и скрытая сеть.' },
    ]),
    sortOrder: 3,
  },
  {
    code: 'conformism_radicalism',
    entityType: 'faction',
    category: 'authority',
    name: 'Конформизм ↔ Радикализм',
    leftPoleLabel: 'Конформизм',
    rightPoleLabel: 'Радикализм',
    leftPoleDescription: 'Следование общим нормам и умеренность формулировок.',
    rightPoleDescription: 'Резкие лозунги и нетерпимость к компромиссам.',
    zonesJson: null,
    sortOrder: 4,
  },
  // --- faction / ideology ---
  {
    code: 'collectivism_individualism',
    entityType: 'faction',
    category: 'ideology',
    name: 'Коллективизм ↔ Индивидуализм',
    leftPoleLabel: 'Коллективизм',
    rightPoleLabel: 'Индивидуализм',
    leftPoleDescription: 'Приоритет группы, общей цели и солидарности.',
    rightPoleDescription: 'Свобода личного выбора и автономия членов.',
    zonesJson: null,
    sortOrder: 5,
  },
  {
    code: 'egalitarianism_elitism',
    entityType: 'faction',
    category: 'ideology',
    name: 'Эгалитаризм ↔ Элитаризм',
    leftPoleLabel: 'Эгалитаризм',
    rightPoleLabel: 'Элитаризм',
    leftPoleDescription: 'Равенство доступа и распределения ролей.',
    rightPoleDescription: 'Лидерство избранных и иерархия компетенций.',
    zonesJson: null,
    sortOrder: 6,
  },
  {
    code: 'dogmatism_pragmatism',
    entityType: 'faction',
    category: 'ideology',
    name: 'Догматизм ↔ Прагматизм',
    leftPoleLabel: 'Догматизм',
    rightPoleLabel: 'Прагматизм',
    leftPoleDescription: 'Негибкие доктрины и символическая чистота.',
    rightPoleDescription: 'Гибкие решения и расчёт последствий.',
    zonesJson: null,
    sortOrder: 7,
  },
  {
    code: 'nationalism_internationalism',
    entityType: 'faction',
    category: 'ideology',
    name: 'Националистичность ↔ Интернационализм',
    leftPoleLabel: 'Националистичность',
    rightPoleLabel: 'Интернационализм',
    leftPoleDescription: 'Приоритет национального сообщества и культуры.',
    rightPoleDescription: 'Трансграничная солидарность и общие ценности.',
    zonesJson: null,
    sortOrder: 8,
  },
  // --- faction / methods ---
  {
    code: 'nonviolence_armed_struggle',
    entityType: 'faction',
    category: 'methods',
    name: 'Ненасилие ↔ Вооружённая борьба',
    leftPoleLabel: 'Ненасилие',
    rightPoleLabel: 'Вооружённая борьба',
    leftPoleDescription: 'Отказ от силовых методов как принцип.',
    rightPoleDescription: 'Допустимость оружия и силовых действий.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Принципиальное ненасилие', description: 'Никакого применения силы даже в ответ.' },
      { from: -49, to: 0, label: 'Гражданское сопротивление', description: 'Бойкоты, забастовки, демонстрации.' },
      { from: 1, to: 50, label: 'Силовые акции', description: 'Конфликты без системной войны.' },
      { from: 51, to: 100, label: 'Вооружённая борьба', description: 'Партизанская или военная линия как стратегия.' },
    ]),
    sortOrder: 9,
  },
  {
    code: 'publicity_conspiracy',
    entityType: 'faction',
    category: 'methods',
    name: 'Публичность ↔ Конспирация',
    leftPoleLabel: 'Публичность',
    rightPoleLabel: 'Конспирация',
    leftPoleDescription: 'Открытые кампании и медиаприсутствие.',
    rightPoleDescription: 'Скрытность, ячейки и минимум следов.',
    zonesJson: null,
    sortOrder: 10,
  },
  {
    code: 'diplomacy_confrontation',
    entityType: 'faction',
    category: 'methods',
    name: 'Дипломатия ↔ Конфронтация',
    leftPoleLabel: 'Дипломатия',
    rightPoleLabel: 'Конфронтация',
    leftPoleDescription: 'Переговоры, коалиции и поиск компромиссов.',
    rightPoleDescription: 'Жёсткое давление и публичные атаки оппонентов.',
    zonesJson: null,
    sortOrder: 11,
  },
  {
    code: 'propaganda_coercion',
    entityType: 'faction',
    category: 'methods',
    name: 'Пропаганда ↔ Принуждение',
    leftPoleLabel: 'Пропаганда',
    rightPoleLabel: 'Принуждение',
    leftPoleDescription: 'Убеждение, мифология, работа с общественным мнением.',
    rightPoleDescription: 'Прямое принуждение, санкции и запугивание.',
    zonesJson: null,
    sortOrder: 12,
  },
  // --- faction / base ---
  {
    code: 'mass_cadre',
    entityType: 'faction',
    category: 'base',
    name: 'Народность ↔ Кадровость',
    leftPoleLabel: 'Народность',
    rightPoleLabel: 'Кадровость',
    leftPoleDescription: 'Массовая база и открытый набор.',
    rightPoleDescription: 'Узкий круг посвящённых и строгий отбор.',
    zonesJson: JSON.stringify([
      { from: -100, to: -50, label: 'Массовое движение', description: 'Десятки тысяч сторонников и активистов.' },
      { from: -49, to: 0, label: 'Широкая партия', description: 'Крупная, но управляемая структура.' },
      { from: 1, to: 50, label: 'Кадровая партия', description: 'Профессиональное ядро и дисциплина.' },
      { from: 51, to: 100, label: 'Орден / узкий круг', description: 'Элитное сообщество с ритуалами и фильтрами.' },
    ]),
    sortOrder: 13,
  },
  {
    code: 'self_financed_patronage',
    entityType: 'faction',
    category: 'base',
    name: 'Самофинансирование ↔ Покровительство',
    leftPoleLabel: 'Самофинансирование',
    rightPoleLabel: 'Покровительство',
    leftPoleDescription: 'Членские взносы и автономные источники.',
    rightPoleDescription: 'Зависимость от спонсоров и внешних покровителей.',
    zonesJson: null,
    sortOrder: 14,
  },
  {
    code: 'secular_religious',
    entityType: 'faction',
    category: 'base',
    name: 'Светскость ↔ Религиозность',
    leftPoleLabel: 'Светскость',
    rightPoleLabel: 'Религиозность',
    leftPoleDescription: 'Секулярная идеология и нейтральный дискурс.',
    rightPoleDescription: 'Религиозные обеты, догматы и ритуал в основе.',
    zonesJson: null,
    sortOrder: 15,
  },
  {
    code: 'class_based_transclass',
    entityType: 'faction',
    category: 'base',
    name: 'Классовость ↔ Надклассовость',
    leftPoleLabel: 'Классовость',
    rightPoleLabel: 'Надклассовость',
    leftPoleDescription: 'Явная опора на класс или сословие.',
    rightPoleDescription: 'Коалиции между разными слоями «ради общего дела».',
    zonesJson: null,
    sortOrder: 16,
  },
];
