// GENERATED — DO NOT EDIT
// Source: shared/seeds/politicalScales.ts via scripts/gen-rust-seeds.mjs
// manifest-hash: f1013f5431d348658e5e4deb87db057550078d1db49415256dbd46898762a948

use rusqlite::{params, Connection};

use crate::error::Result;

#[derive(Clone, Copy)]
struct SeedScale {
    code: &'static str,
    entity_type: &'static str,
    category: &'static str,
    name: &'static str,
    left_pole_label: &'static str,
    right_pole_label: &'static str,
    left_pole_description: &'static str,
    right_pole_description: &'static str,
    zones_json: Option<&'static str>,
    sort_order: i32,
}

const SYSTEM_SCALES: &[SeedScale] = &[
    SeedScale {
        code: "authoritarianism_democracy",
        entity_type: "state",
        category: "power",
        name: "Авторитаризм ↔ Демократия",
        left_pole_label: "Авторитаризм",
        right_pole_label: "Демократия",
        left_pole_description: "Сильная концентрация власти, ограниченные институты участия.",
        right_pole_description: "Широкое политическое участие и конкурентные выборы.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-66,\"label\":\"Тирания / диктатура\",\"description\":\"Правление одного центра без эффективных ограничений.\"},{\"from\":-65,\"to\":-20,\"label\":\"Авторитарный режим\",\"description\":\"Формальные институты есть, но оппозиция слаба.\"},{\"from\":-19,\"to\":19,\"label\":\"Гибридный режим\",\"description\":\"Смесь демократических и авторитарных практик.\"},{\"from\":20,\"to\":65,\"label\":\"Представительная демократия\",\"description\":\"Выборы и парламент как основа легитимности.\"},{\"from\":66,\"to\":100,\"label\":\"Прямая демократия\",\"description\":\"Максимум прямого участия граждан в решениях.\"}]"#,
        ),
        sort_order: 1,
    },
    SeedScale {
        code: "centralization_federalization",
        entity_type: "state",
        category: "power",
        name: "Централизация ↔ Федерализация",
        left_pole_label: "Централизация",
        right_pole_label: "Федерализация",
        left_pole_description: "Решения и ресурсы сосредоточены в столице.",
        right_pole_description: "Регионы и субъекты обладают существенной автономией.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Унитарное государство\",\"description\":\"Единая административная вертикаль.\"},{\"from\":-49,\"to\":20,\"label\":\"Деволюция\",\"description\":\"Постепенная передача полномочий вниз.\"},{\"from\":21,\"to\":65,\"label\":\"Федерация\",\"description\":\"Чёткое разделение уровней власти.\"},{\"from\":66,\"to\":100,\"label\":\"Конфедерация\",\"description\":\"Союз с высокой независимостью членов.\"}]"#,
        ),
        sort_order: 2,
    },
    SeedScale {
        code: "monarchy_republic",
        entity_type: "state",
        category: "power",
        name: "Монархия ↔ Республика",
        left_pole_label: "Монархия",
        right_pole_label: "Республика",
        left_pole_description: "Наследуемая верховная власть и символика престола.",
        right_pole_description: "Выборные органы и отсутствие наследственной власти.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-66,\"label\":\"Абсолютная монархия\",\"description\":\"Монарх — главный источник законов.\"},{\"from\":-65,\"to\":-20,\"label\":\"Конституционная монархия\",\"description\":\"Парламент и закон ограничивают монарха.\"},{\"from\":-19,\"to\":19,\"label\":\"Смешанная форма\",\"description\":\"Черты монархии и республики в равновесии.\"},{\"from\":20,\"to\":65,\"label\":\"Парламентская республика\",\"description\":\"Правительство отвечает перед парламентом.\"},{\"from\":66,\"to\":100,\"label\":\"Президентская республика\",\"description\":\"Сильная исполнительная власть президента.\"}]"#,
        ),
        sort_order: 3,
    },
    SeedScale {
        code: "theocracy_secularism",
        entity_type: "state",
        category: "power",
        name: "Теократия ↔ Секуляризм",
        left_pole_label: "Теократия",
        right_pole_label: "Секуляризм",
        left_pole_description: "Религиозное право и духовенство в основе государства.",
        right_pole_description: "Нейтральность государства в религиозных вопросах.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Теократия\",\"description\":\"Богословские нормы определяют закон.\"},{\"from\":-49,\"to\":-10,\"label\":\"Государственная религия\",\"description\":\"Официальный культ и привилегии церкви.\"},{\"from\":-9,\"to\":30,\"label\":\"Религия в публичной жизни\",\"description\":\"Заметное присутствие религии в символике и нормах.\"},{\"from\":31,\"to\":100,\"label\":\"Светское государство\",\"description\":\"Разделение сфер и равенство конфессий.\"}]"#,
        ),
        sort_order: 4,
    },
    SeedScale {
        code: "police_state_civil_liberties",
        entity_type: "state",
        category: "society",
        name: "Полицейское государство ↔ Гражданские свободы",
        left_pole_label: "Полицейское государство",
        right_pole_label: "Гражданские свободы",
        left_pole_description: "Сильный контроль, ограничения приватности и собраний.",
        right_pole_description: "Широкие права на слово, ассоциации и судебную защиту.",
        zones_json: None,
        sort_order: 5,
    },
    SeedScale {
        code: "traditionalism_progressivism",
        entity_type: "state",
        category: "society",
        name: "Традиционализм ↔ Прогрессивизм",
        left_pole_label: "Традиционализм",
        right_pole_label: "Прогрессивизм",
        left_pole_description: "Опора на устойчивые нормы, роль общины и религии.",
        right_pole_description: "Ориентация на реформы, права меньшинств и новые нормы.",
        zones_json: None,
        sort_order: 6,
    },
    SeedScale {
        code: "estate_meritocracy",
        entity_type: "state",
        category: "society",
        name: "Сословность ↔ Меритократия",
        left_pole_label: "Сословность",
        right_pole_label: "Меритократия",
        left_pole_description: "Статус и доступ к власти зависят от происхождения.",
        right_pole_description: "Карьера и роли по компетенции и заслугам.",
        zones_json: None,
        sort_order: 7,
    },
    SeedScale {
        code: "monoethnic_multicultural",
        entity_type: "state",
        category: "society",
        name: "Моноэтничность ↔ Мультикультурализм",
        left_pole_label: "Моноэтничность",
        right_pole_label: "Мультикультурализм",
        left_pole_description: "Один культурный образ государства и ассимиляционные ожидания.",
        right_pole_description: "Поддержка культурного разнообразия и интеграции.",
        zones_json: None,
        sort_order: 8,
    },
    SeedScale {
        code: "planned_market",
        entity_type: "state",
        category: "economy",
        name: "Плановая ↔ Рыночная экономика",
        left_pole_label: "Плановая",
        right_pole_label: "Рыночная",
        left_pole_description: "Централизованное планирование и квоты.",
        right_pole_description: "Цены и конкуренция как основной регулятор.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Командно-административная\",\"description\":\"Планы и распределение сверху.\"},{\"from\":-49,\"to\":-10,\"label\":\"Регулируемая плановая\",\"description\":\"План с местом для рыночных элементов.\"},{\"from\":-9,\"to\":30,\"label\":\"Смешанная экономика\",\"description\":\"Государство и рынок делят ключевые рычаги.\"},{\"from\":31,\"to\":70,\"label\":\"Рыночная с регулированием\",\"description\":\"Рынок доминирует, регулирование точечное.\"},{\"from\":71,\"to\":100,\"label\":\"Свободный рынок\",\"description\":\"Минимум барьеров и вмешательств.\"}]"#,
        ),
        sort_order: 9,
    },
    SeedScale {
        code: "protectionism_free_trade",
        entity_type: "state",
        category: "economy",
        name: "Протекционизм ↔ Свободная торговля",
        left_pole_label: "Протекционизм",
        right_pole_label: "Свободная торговля",
        left_pole_description: "Тарифы и квоты для защиты отечественных отраслей.",
        right_pole_description: "Минимальные барьеры для импорта и экспорта.",
        zones_json: None,
        sort_order: 10,
    },
    SeedScale {
        code: "agrarian_industrial",
        entity_type: "state",
        category: "economy",
        name: "Аграрность ↔ Индустриализация",
        left_pole_label: "Аграрность",
        right_pole_label: "Индустриализация",
        left_pole_description: "Сельское хозяйство и земля как основа экономики.",
        right_pole_description: "Промышленность, сервисы и инновации доминируют.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Аграрное общество\",\"description\":\"Большинство занято землёй и природными циклами.\"},{\"from\":-49,\"to\":0,\"label\":\"Аграрно-промышленное\",\"description\":\"Переходные отрасли и урбанизация.\"},{\"from\":1,\"to\":50,\"label\":\"Индустриальное\",\"description\":\"Заводы, инфраструктура, массовое производство.\"},{\"from\":51,\"to\":100,\"label\":\"Постиндустриальное\",\"description\":\"Услуги, ИТ, наука и глобальные цепочки.\"}]"#,
        ),
        sort_order: 11,
    },
    SeedScale {
        code: "state_private_property",
        entity_type: "state",
        category: "economy",
        name: "Казённая собственность ↔ Частная собственность",
        left_pole_label: "Казённая собственность",
        right_pole_label: "Частная собственность",
        left_pole_description: "Государственные и общинные активы в центре модели.",
        right_pole_description: "Частные права и рынок активов как норма.",
        zones_json: None,
        sort_order: 12,
    },
    SeedScale {
        code: "isolationism_expansionism",
        entity_type: "state",
        category: "foreign",
        name: "Изоляционизм ↔ Экспансионизм",
        left_pole_label: "Изоляционизм",
        right_pole_label: "Экспансионизм",
        left_pole_description: "Минимальное внешнее вмешательство и автономия.",
        right_pole_description: "Активное расширение влияния и интересов за рубежом.",
        zones_json: None,
        sort_order: 13,
    },
    SeedScale {
        code: "militarism_pacifism",
        entity_type: "state",
        category: "foreign",
        name: "Милитаризм ↔ Пацифизм",
        left_pole_label: "Милитаризм",
        right_pole_label: "Пацифизм",
        left_pole_description: "Высокая роль армии и силовых структур в политике.",
        right_pole_description: "Приоритет дипломатии и отказ от силовых решений.",
        zones_json: None,
        sort_order: 14,
    },
    SeedScale {
        code: "sovereignty_integration",
        entity_type: "state",
        category: "foreign",
        name: "Суверенитет ↔ Интеграция",
        left_pole_label: "Суверенитет",
        right_pole_label: "Интеграция",
        left_pole_description: "Полный контроль над законами и границами.",
        right_pole_description: "Уступка полномочий союзам и наднациональным органам.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Полная независимость\",\"description\":\"Нет обязательств, выше национальный суверенитет.\"},{\"from\":-49,\"to\":0,\"label\":\"Союзнические отношения\",\"description\":\"Договоры и координация без уступки суверенитета.\"},{\"from\":1,\"to\":50,\"label\":\"Конфедеративные структуры\",\"description\":\"Совместные институты с разделением компетенций.\"},{\"from\":51,\"to\":100,\"label\":\"Наднациональный союз\",\"description\":\"Глубокая интеграция законов и политик.\"}]"#,
        ),
        sort_order: 15,
    },
    SeedScale {
        code: "xenophobia_openness",
        entity_type: "state",
        category: "foreign",
        name: "Ксенофобия ↔ Открытость",
        left_pole_label: "Ксенофобия",
        right_pole_label: "Открытость",
        left_pole_description: "Опасение чужого, жёсткие барьеры для приезжих.",
        right_pole_description: "Миграция и обмен как норма и ресурс.",
        zones_json: None,
        sort_order: 16,
    },
    SeedScale {
        code: "loyalism_opposition",
        entity_type: "faction",
        category: "authority",
        name: "Лоялизм ↔ Оппозиция",
        left_pole_label: "Лоялизм",
        right_pole_label: "Оппозиция",
        left_pole_description: "Поддержка текущей власти и легитимных институтов.",
        right_pole_description: "Критика режима и стремление к смене курса.",
        zones_json: None,
        sort_order: 1,
    },
    SeedScale {
        code: "reformism_revolution",
        entity_type: "faction",
        category: "authority",
        name: "Реформизм ↔ Революционность",
        left_pole_label: "Реформизм",
        right_pole_label: "Революционность",
        left_pole_description: "Постепенные изменения в рамках системы.",
        right_pole_description: "Резкий разрыв с прежним порядком.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Консерваторы\",\"description\":\"Сопротивление переменам, сохранение статус-кво.\"},{\"from\":-49,\"to\":0,\"label\":\"Реформисты\",\"description\":\"Эволюция правил и институтов.\"},{\"from\":1,\"to\":50,\"label\":\"Радикальные реформисты\",\"description\":\"Быстрые преобразования без насильственного переворота.\"},{\"from\":51,\"to\":100,\"label\":\"Революционеры\",\"description\":\"Насильственная смена системы как допустимая цель.\"}]"#,
        ),
        sort_order: 2,
    },
    SeedScale {
        code: "legalism_underground",
        entity_type: "faction",
        category: "authority",
        name: "Легализм ↔ Подпольность",
        left_pole_label: "Легализм",
        right_pole_label: "Подпольность",
        left_pole_description: "Публичная регистрация и работа в правовом поле.",
        right_pole_description: "Тайные структуры и обход официальных запретов.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Официальная партия\",\"description\":\"Полностью легальный статус и доступ к институтам.\"},{\"from\":-49,\"to\":0,\"label\":\"Полулегальное движение\",\"description\":\"Частичная легальность, зона серых схем.\"},{\"from\":1,\"to\":50,\"label\":\"Нелегальное движение\",\"description\":\"Запрещённая деятельность без глубокой конспирации.\"},{\"from\":51,\"to\":100,\"label\":\"Подпольная организация\",\"description\":\"Строгая конспирация и скрытая сеть.\"}]"#,
        ),
        sort_order: 3,
    },
    SeedScale {
        code: "conformism_radicalism",
        entity_type: "faction",
        category: "authority",
        name: "Конформизм ↔ Радикализм",
        left_pole_label: "Конформизм",
        right_pole_label: "Радикализм",
        left_pole_description: "Следование общим нормам и умеренность формулировок.",
        right_pole_description: "Резкие лозунги и нетерпимость к компромиссам.",
        zones_json: None,
        sort_order: 4,
    },
    SeedScale {
        code: "collectivism_individualism",
        entity_type: "faction",
        category: "ideology",
        name: "Коллективизм ↔ Индивидуализм",
        left_pole_label: "Коллективизм",
        right_pole_label: "Индивидуализм",
        left_pole_description: "Приоритет группы, общей цели и солидарности.",
        right_pole_description: "Свобода личного выбора и автономия членов.",
        zones_json: None,
        sort_order: 5,
    },
    SeedScale {
        code: "egalitarianism_elitism",
        entity_type: "faction",
        category: "ideology",
        name: "Эгалитаризм ↔ Элитаризм",
        left_pole_label: "Эгалитаризм",
        right_pole_label: "Элитаризм",
        left_pole_description: "Равенство доступа и распределения ролей.",
        right_pole_description: "Лидерство избранных и иерархия компетенций.",
        zones_json: None,
        sort_order: 6,
    },
    SeedScale {
        code: "dogmatism_pragmatism",
        entity_type: "faction",
        category: "ideology",
        name: "Догматизм ↔ Прагматизм",
        left_pole_label: "Догматизм",
        right_pole_label: "Прагматизм",
        left_pole_description: "Негибкие доктрины и символическая чистота.",
        right_pole_description: "Гибкие решения и расчёт последствий.",
        zones_json: None,
        sort_order: 7,
    },
    SeedScale {
        code: "nationalism_internationalism",
        entity_type: "faction",
        category: "ideology",
        name: "Националистичность ↔ Интернационализм",
        left_pole_label: "Националистичность",
        right_pole_label: "Интернационализм",
        left_pole_description: "Приоритет национального сообщества и культуры.",
        right_pole_description: "Трансграничная солидарность и общие ценности.",
        zones_json: None,
        sort_order: 8,
    },
    SeedScale {
        code: "nonviolence_armed_struggle",
        entity_type: "faction",
        category: "methods",
        name: "Ненасилие ↔ Вооружённая борьба",
        left_pole_label: "Ненасилие",
        right_pole_label: "Вооружённая борьба",
        left_pole_description: "Отказ от силовых методов как принцип.",
        right_pole_description: "Допустимость оружия и силовых действий.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Принципиальное ненасилие\",\"description\":\"Никакого применения силы даже в ответ.\"},{\"from\":-49,\"to\":0,\"label\":\"Гражданское сопротивление\",\"description\":\"Бойкоты, забастовки, демонстрации.\"},{\"from\":1,\"to\":50,\"label\":\"Силовые акции\",\"description\":\"Конфликты без системной войны.\"},{\"from\":51,\"to\":100,\"label\":\"Вооружённая борьба\",\"description\":\"Партизанская или военная линия как стратегия.\"}]"#,
        ),
        sort_order: 9,
    },
    SeedScale {
        code: "publicity_conspiracy",
        entity_type: "faction",
        category: "methods",
        name: "Публичность ↔ Конспирация",
        left_pole_label: "Публичность",
        right_pole_label: "Конспирация",
        left_pole_description: "Открытые кампании и медиаприсутствие.",
        right_pole_description: "Скрытность, ячейки и минимум следов.",
        zones_json: None,
        sort_order: 10,
    },
    SeedScale {
        code: "diplomacy_confrontation",
        entity_type: "faction",
        category: "methods",
        name: "Дипломатия ↔ Конфронтация",
        left_pole_label: "Дипломатия",
        right_pole_label: "Конфронтация",
        left_pole_description: "Переговоры, коалиции и поиск компромиссов.",
        right_pole_description: "Жёсткое давление и публичные атаки оппонентов.",
        zones_json: None,
        sort_order: 11,
    },
    SeedScale {
        code: "propaganda_coercion",
        entity_type: "faction",
        category: "methods",
        name: "Пропаганда ↔ Принуждение",
        left_pole_label: "Пропаганда",
        right_pole_label: "Принуждение",
        left_pole_description: "Убеждение, мифология, работа с общественным мнением.",
        right_pole_description: "Прямое принуждение, санкции и запугивание.",
        zones_json: None,
        sort_order: 12,
    },
    SeedScale {
        code: "mass_cadre",
        entity_type: "faction",
        category: "base",
        name: "Народность ↔ Кадровость",
        left_pole_label: "Народность",
        right_pole_label: "Кадровость",
        left_pole_description: "Массовая база и открытый набор.",
        right_pole_description: "Узкий круг посвящённых и строгий отбор.",
        zones_json: Some(
            r#"[{\"from\":-100,\"to\":-50,\"label\":\"Массовое движение\",\"description\":\"Десятки тысяч сторонников и активистов.\"},{\"from\":-49,\"to\":0,\"label\":\"Широкая партия\",\"description\":\"Крупная, но управляемая структура.\"},{\"from\":1,\"to\":50,\"label\":\"Кадровая партия\",\"description\":\"Профессиональное ядро и дисциплина.\"},{\"from\":51,\"to\":100,\"label\":\"Орден / узкий круг\",\"description\":\"Элитное сообщество с ритуалами и фильтрами.\"}]"#,
        ),
        sort_order: 13,
    },
    SeedScale {
        code: "self_financed_patronage",
        entity_type: "faction",
        category: "base",
        name: "Самофинансирование ↔ Покровительство",
        left_pole_label: "Самофинансирование",
        right_pole_label: "Покровительство",
        left_pole_description: "Членские взносы и автономные источники.",
        right_pole_description: "Зависимость от спонсоров и внешних покровителей.",
        zones_json: None,
        sort_order: 14,
    },
    SeedScale {
        code: "secular_religious",
        entity_type: "faction",
        category: "base",
        name: "Светскость ↔ Религиозность",
        left_pole_label: "Светскость",
        right_pole_label: "Религиозность",
        left_pole_description: "Секулярная идеология и нейтральный дискурс.",
        right_pole_description: "Религиозные обеты, догматы и ритуал в основе.",
        zones_json: None,
        sort_order: 15,
    },
    SeedScale {
        code: "class_based_transclass",
        entity_type: "faction",
        category: "base",
        name: "Классовость ↔ Надклассовость",
        left_pole_label: "Классовость",
        right_pole_label: "Надклассовость",
        left_pole_description: "Явная опора на класс или сословие.",
        right_pole_description: "Коалиции между разными слоями «ради общего дела».",
        zones_json: None,
        sort_order: 16,
    },
];

pub fn seed_system_scales(connection: &Connection) -> Result<()> {
    let count: i64 = connection.query_row(
        "SELECT COUNT(*) FROM political_scales WHERE is_system = 1",
        [],
        |row| row.get(0),
    )?;
    if count > 0 {
        return Ok(());
    }

    let mut insert = connection.prepare(
        r#"
        INSERT OR IGNORE INTO political_scales (
            code, entity_type, category, name,
            left_pole_label, right_pole_label,
            left_pole_description, right_pole_description,
            icon, zones_json, is_system, project_id, sort_order
        ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, NULL, ?9, 1, NULL, ?10)
        "#,
    )?;

    for scale in SYSTEM_SCALES {
        insert.execute(params![
            scale.code,
            scale.entity_type,
            scale.category,
            scale.name,
            scale.left_pole_label,
            scale.right_pole_label,
            scale.left_pole_description,
            scale.right_pole_description,
            scale.zones_json,
            scale.sort_order
        ])?;
    }

    Ok(())
}
