mod commands;
mod db;
mod error;
pub mod models;
mod paths;
pub mod repositories;
pub mod services;
pub mod specta;

use db::connection::{open_database, DatabaseState};
use db::migrations::run_migrations;
use tauri::Manager;

pub fn run() {
    tauri::Builder::default()
        .setup(|app| {
            let connection = open_database(app.handle())
                .map_err(|err| std::io::Error::other(err.to_string()))?;

            run_migrations(&connection).map_err(|err| std::io::Error::other(err.to_string()))?;

            app.manage(DatabaseState::new(connection));
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::ambitions::ambitions_get_catalog_command,
            commands::ambitions::ambitions_create_command,
            commands::ambitions::ambitions_update_command,
            commands::ambitions::ambitions_update_exclusions_command,
            commands::ambitions::ambitions_delete_command,
            commands::ambitions::ambitions_get_faction_ambitions_command,
            commands::ambitions::ambitions_assign_faction_ambition_command,
            commands::ambitions::ambitions_unassign_faction_ambition_command,
            commands::app::app_health_command,
            commands::branches::branches_list_command,
            commands::branches::branches_create_command,
            commands::branches::branches_update_command,
            commands::branches::branches_delete_command,
            commands::character_traits::character_traits_list_command,
            commands::character_traits::character_traits_get_assigned_command,
            commands::character_traits::character_traits_assign_command,
            commands::character_traits::character_traits_unassign_command,
            commands::character_traits::character_traits_create_command,
            commands::character_traits::character_traits_update_exclusions_command,
            commands::character_traits::character_traits_delete_command,
            commands::characters::characters_list_command,
            commands::characters::characters_get_command,
            commands::characters::characters_create_command,
            commands::characters::characters_update_command,
            commands::characters::characters_delete_command,
            commands::characters::characters_set_tags_command,
            commands::characters::characters_relationships_list_command,
            commands::characters::characters_relationships_create_command,
            commands::characters::characters_relationships_update_command,
            commands::characters::characters_relationships_delete_command,
            commands::characters::characters_graph_command,
            commands::dogmas::dogmas_list_command,
            commands::dogmas::dogmas_get_command,
            commands::dogmas::dogmas_create_command,
            commands::dogmas::dogmas_update_command,
            commands::dogmas::dogmas_delete_command,
            commands::dogmas::dogmas_reorder_command,
            commands::dogmas::dogmas_set_tags_command,
            commands::dynasties::dynasties_list_command,
            commands::dynasties::dynasties_get_command,
            commands::dynasties::dynasties_create_command,
            commands::dynasties::dynasties_update_command,
            commands::dynasties::dynasties_delete_command,
            commands::dynasties::dynasties_set_tags_command,
            commands::dynasties::dynasties_add_member_command,
            commands::dynasties::dynasties_update_member_command,
            commands::dynasties::dynasties_remove_member_command,
            commands::dynasties::dynasties_save_graph_positions_command,
            commands::dynasties::dynasties_add_family_link_command,
            commands::dynasties::dynasties_delete_family_link_command,
            commands::dynasties::dynasties_add_event_command,
            commands::dynasties::dynasties_update_event_command,
            commands::dynasties::dynasties_delete_event_command,
            commands::dynasties::dynasties_reorder_events_command,
            commands::factions::factions_list_command,
            commands::factions::factions_get_command,
            commands::factions::factions_create_command,
            commands::factions::factions_update_command,
            commands::factions::factions_delete_command,
            commands::factions::factions_set_tags_command,
            commands::factions::factions_ranks_list_command,
            commands::factions::factions_ranks_create_command,
            commands::factions::factions_ranks_update_command,
            commands::factions::factions_ranks_delete_command,
            commands::factions::factions_members_list_command,
            commands::factions::factions_members_create_command,
            commands::factions::factions_members_update_command,
            commands::factions::factions_members_delete_command,
            commands::factions::factions_custom_metrics_replace_command,
            commands::factions::factions_compare_command,
            commands::factions::factions_relations_list_command,
            commands::factions::factions_relations_create_command,
            commands::factions::factions_relations_update_command,
            commands::factions::factions_relations_delete_command,
            commands::factions::factions_graph_command,
            commands::factions::factions_policies_list_command,
            commands::factions::factions_policies_create_command,
            commands::factions::factions_policies_update_command,
            commands::factions::factions_policies_delete_command,
            commands::graph_layouts::graph_layout_get_command,
            commands::graph_layouts::graph_layout_upsert_command,
            commands::graph_layouts::graph_layout_delete_command,
            commands::maps::maps_get_root_command,
            commands::maps::maps_get_tree_command,
            commands::maps::maps_get_command,
            commands::maps::maps_create_command,
            commands::maps::maps_update_command,
            commands::maps::maps_delete_command,
            commands::maps::maps_markers_list_command,
            commands::maps::maps_markers_create_command,
            commands::maps::maps_markers_update_command,
            commands::maps::maps_markers_delete_command,
            commands::maps::maps_territories_list_command,
            commands::maps::maps_territories_create_command,
            commands::maps::maps_territories_update_command,
            commands::maps::maps_territories_delete_command,
            commands::maps::maps_territory_summaries_list_command,
            commands::projects::projects_list_command,
            commands::projects::projects_get_command,
            commands::projects::projects_create_command,
            commands::projects::projects_update_command,
            commands::projects::projects_delete_command,
            commands::search::search_query_command,
            commands::political_scales::political_scales_list_command,
            commands::political_scales::political_scales_create_command,
            commands::political_scales::political_scales_update_command,
            commands::political_scales::political_scales_delete_command,
            commands::political_scales::political_scale_assignments_list_command,
            commands::political_scales::political_scale_assignments_replace_command,
            commands::political_scales::political_scale_assignments_delete_command,
            commands::notes::notes_list_command,
            commands::notes::notes_get_command,
            commands::notes::notes_create_command,
            commands::notes::notes_update_command,
            commands::notes::notes_delete_command,
            commands::notes::notes_set_tags_command,
            commands::tags::tags_list_command,
            commands::tags::tags_create_command,
            commands::tags::tags_delete_command,
            commands::timeline::timeline_list_command,
            commands::timeline::timeline_get_command,
            commands::timeline::timeline_create_command,
            commands::timeline::timeline_update_command,
            commands::timeline::timeline_delete_command,
            commands::timeline::timeline_reorder_command,
            commands::timeline::timeline_set_tags_command,
            commands::wiki::wiki_links_list_command,
            commands::wiki::wiki_links_create_command,
            commands::wiki::wiki_links_delete_command,
            commands::wiki::wiki_categories_list_command
        ])
        .run(tauri::generate_context!())
        .expect("failed to run tauri application");
}
